stages:
  - publish
  - deploy

workflow:
  rules: 
    - if: $CI_COMMIT_BRANCH == "main"

publish:
  image: docker:stable
  stage: publish
  services: 
    - docker:dind
  before_script:
    - docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 
  script:
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_IMAGE:$TAG_PROD
    - docker build --target=production -t $CI_REGISTRY_IMAGE:$TAG_PROD --build-arg "VITE_PROTOCOL=https" --build-arg "VITE_BACK_PORT=3000" --build-arg "VITE_BACK_HOST=ec2-15-237-216-144.eu-west-3.compute.amazonaws.com" .
    - docker push $CI_REGISTRY_IMAGE:$TAG_PROD

deploy:
  image: alpine:latest
  stage: deploy
  environment:
    name: production
    url: http://ec2-15-237-216-144.eu-west-3.compute.amazonaws.com
  script:
    - chmod og= $ID_RSA
    - echo $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $AWS_USER@$AWS_DNS "docker login $CI_REGISTRY -u '$CI_REGISTRY_USER' -p '$CI_REGISTRY_PASSWORD'"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $AWS_USER@$AWS_DNS "docker pull $CI_REGISTRY_IMAGE:$TAG_PROD"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $AWS_USER@$AWS_DNS "docker container rm -f front_chappy_prod || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $AWS_USER@$AWS_DNS "docker-compose up -d"